# docker-compose.yml (in the project root)
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    networks:
      - vlm_network
    environment:
      # These URLs point to the backend service within the Docker network
      - NEXT_PUBLIC_SIGNALING_SERVER_URL=http://backend:4000
      - NEXT_PUBLIC_INFERENCE_SERVER_URL=http://backend:8000
      # This should be your laptop's IP or a tunnel for the QR code
      - NEXT_PUBLIC_LAPTOP_URL=http://YOUR_LAPTOP_IP:3000

  backend:
    build:
      context: ./server
    ports:
      - "4000:4000"
      - "8000:8000"
    networks:
      - vlm_network

networks:
  vlm_network:
    driver: bridge